version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Labels on pull requests for security and version updates
    labels:
      - "type/dependencies"
    # Disable version updates for npm dependencies (we only want security updates)
    open-pull-requests-limit: 0
